i7e:
  image: gcr.io/clearvision-edge-prod/i7e/i7e-base:x.y.z
  imagePullPolicy: IfNotPresent
  hostNetwork: true
  serviceAccountJSON: null
  gpuLimit: true
  cameras: []
  segmentation:
    enabled: false
  objectDetection:
    enabled: false
  classification:
    enabled: false
  sources:
    files:
      enabled: true
      srtKey: goq1lUi3QQLc81NlEjXpb8yQQdfKsrRq
      srtURI: srt://dev001.video.cvedge.io:8896
  logging:
    pipeline: INFO
    preprocess: INFO
    postprocess: INFO
    postprocessResults: INFO
    plc: INFO
