x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '1.3.0'
  publishedVersionMetadata:
    releaseNote: >-
      i7e Version 4.0.3 release with GPU support.

  clusterConstraints:
    resources:
    - requests:
        gpu: 
          nvidia.com/gpu: {}
    assistedClusterCreation:
      type: DISABLED
      creationGuidance: "Create a COS Cluster with nvidia-drivers preloaded. Head to https://github.com/clearobject/clearvision-edge-public/blob/main/README.MD to understand how to create a cluster"

  images:
    i7e-base:
      properties:
        i7e-baseImage:
          type: FULL
          default: gcr.io/clearvision-edge-prod/i7e/i7e-base:1.3.0

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  i7e.image:
    type: string
    default: gcr.io/clearvision-edge-prod/i7e/i7e-base:1.3.0
  i7e.gpuLimit:
    default: true
    type: boolean
  i7e.hostNetwork:
    default: true
    type: boolean
  i7e.imagePullPolicy:
    default: IfNotPresent
    type: string
  i7e.serviceAccountJSON:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >-
          The service account used by i7e to interact with Kubernetes resources.
          IMPORTANT: It needs sufficient permissions to manage deployments, services, and other resources in the namespace.
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: view
  i7e.segmentation.enabled:
    default: true
    type: boolean
  i7e.objectDetection.enabled:
    default: false
    type: boolean
  i7e.classification.enabled:
    default: false
    type: boolean
  i7e.sources.files.enabled:
    default: true
    type: boolean
  i7e.sources.files.srtKey:
    default: goq1lUi3QQLc81NlEjXpb8yQQdfKsrRq
    type: string
  i7e.sources.files.srtURI:
    default: srt://dev001.video.cvedge.io:8896
    type: string
  i7e.logging.pipeline:
    type: string
    title: Pipeline logging
    enum:
    - INFO
    - DEBUG
    - WARN
    - CRITICAL
  i7e.logging.preprocess:
    type: string
    title: Preprocess logging
    enum:
    - INFO
    - DEBUG
    - WARN
    - CRITICAL
  i7e.logging.postprocess:
    type: string
    title: Postprocess logging
    enum:
    - INFO
    - DEBUG
    - WARN
    - CRITICAL
  i7e.logging.postprocessResults:
    type: string
    title: Postprocess Results logging
    enum:
    - INFO
    - DEBUG
    - WARN
    - CRITICAL
  i7e.logging.plc:
    type: string
    title: Pipeline logging
    enum:
    - INFO
    - DEBUG
    - WARN
    - CRITICAL
  

required:
- name
- namespace
- i7e.serviceAccountJSON
- i7e.imagePullPolicy
- i7e.hostNetwork
- i7e.gpuLimit
- i7e.segmentation.enabled
- i7e.objectDetection.enabled
- i7e.classification.enabled
- i7e.sources.files.enabled
- i7e.sources.files.srtKey
- i7e.sources.files.srtURI