##########################################################################
#  Copyright 2024 ClearObject, Inc. All Rights Reserved.                 #
#  You may not use, distribute, or modify this code unless otherwise     #
#  specified in a mutually agreed upon license agreement between you     #
#  and ClearObject, Inc.                                                 #
##########################################################################
{{ if .Values.i7e.serviceAccountJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: google-secret
data:
  cloud.json: {{ .Values.i7e.serviceAccountJSON | b64enc }}
{{ end }}
