FROM gcr.io/clearvision-edge-prod/i7e/i7e-base:1.8.0

LABEL com.googleapis.cloudmarketplace.product.service.name="com.clearobject.clearvision"
RUN apt-get update && \
    apt-get install -y --no-install-recommends openssh-server
WORKDIR /app
ENTRYPOINT [ ]
CMD [ ]
