FROM gcr.io/clearvision-edge-prod/i7e/i7e-base:1.8.4

LABEL com.googleapis.cloudmarketplace.product.service.name="com.clearobject.clearvision"

RUN apt-get update && apt-get dist-upgrade -fy && rm -rf /var/lib/apt/lists/*
