##########################################################################
#  Copyright 2024 ClearObject, Inc. All Rights Reserved.                 #
#  You may not use, distribute, or modify this code unless otherwise     #
#  specified in a mutually agreed upon license agreement between you     #
#  and ClearObject, Inc.                                                 #
##########################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: i7e-config
data: 
  config.yaml: |
    version: 4.0.3
    livenessLoggingEnabled: false
    deviceName: Unknown
    templates:
      reusable-thing: &REUSABLE_THING
        someKey: someValue
        someOtherKey: someOtherValue
    logging:
      pipeline: {{ .Values.i7e.logging.pipeline }}
      preprocess: {{ .Values.i7e.logging.preprocess }}
      postprocess: {{ .Values.i7e.logging.postprocess }}
      postprocessResults: {{ .Values.i7e.logging.postprocessResults }}
      azureIOT: INFO
      azureEventHub: INFO
      plc: {{ .Values.i7e.logging.plc }}
      googlePubsub: {{ .Values.i7e.logging.plc }}
      snap7: INFO
      googleCloud: WARN
      streamer: INFO
      rabbit: INFO
    imageCapture:
      passive:
        azure:
          enabled: false
          uploadMaxFPS: 5
          uploadPrefix: i7e-uploads/{device_name}/passive
          accountName: xxxxxxxxxxxxxx
          containerName: container1
        google:
          enabled: false
          uploadMaxFPS: 5
          uploadPrefix: "{device_name}/passive"
          bucketName: clearvision-edge-prod-upload
        file:
          enabled: false
          uploadMaxFPS: 5
          uploadPrefix: /var/spool/i7e-uploads/passive
          maxSize: 67108864
      active:
        azure:
          enabled: false
          uploadMaxFPS: 5
          uploadPrefix: i7e-uploads/{device_name}/active
          accountName: xxxxxxxxxxxxxx
          containerName: container1
        google:
          enabled: false
          uploadMaxFPS: 5
          uploadPrefix: "{device_name}/active"
          bucketName: clearvision-edge-prod-upload
        file:
          enabled: false
          uploadMaxFPS: 5
          uploadPrefix: /var/spool/i7e-uploads/active
          maxSize: 67108864
    inferenceLogging:
      - rabbit:
          enabled: false
          host: localhost
          port: 5672
          vhost: /
          exchange_name: test
          organization_id: clearobject
          credentials_username: guest
          credentials_password: guest
      - azureEventHub:
          enabled: false
          inference:
            connectString: "Endpoint=sb://xxxxxxxxx;SharedAccessKeyName=publisher;SharedAccessKey=xxxxxxx;\
              EntityPath=i7e-edge-dev-inference"
            eventHubName: xxxxxxxxx
            maximumMessagesPerBatch: 128
            maximumPayloadSize: 4096
          liveness:
            connectString: "Endpoint=sb://xxxxxxxxx;SharedAccessKeyName=publisher;SharedAccessKey=xxxxxxx;\
              EntityPath=i7e-edge-dev-liveness"
            eventHubName: xxxxxxxxx
            maximumMessagesPerBatch: 128
            maximumPayloadSize: 4096
      - azureIOT:
          enabled: false
          connectString: HostName=xxxxxxxxxxxx-hub.azure-devices.net;DeviceId=xxxxx;SharedAccessKey=bm90IGEgcmVhbCBrZXk=
      - googlePubsub:
          enabled: false
          batchInterval: 30
          inferenceTopic: "projects/clearvision-edge-prod/topics/infer-{device_name}"
          livenessTopic: "projects/clearvision-edge-prod/topics/liveness-{device_name}"
      - plc:
          enabled: false
          address: 127.0.0.1
          port: 9999
          slot: 0
          rack: 0
          block: 0
          offset: 24
          # heartbeatReadOffset: 2
          # heartbeatWriteOffset: 200
          cameraOffset: 196
          inferenceOffset: 198
          # heartbeatFrequency: 1
    streaming:
      default: REMOTE
    sources:
      - files:
          enabled: {{ .Values.i7e.sources.files.enabled }}
          validateSize: false
          width: 1456
          height: 1088
          directory: /var/spool/i7e/video/longdrive
          filePattern: drive-%05d.png
          framerate: 20/1
          fileIndex: 0
          deadmanSeconds: 10
          srtKey: {{ .Values.i7e.sources.files.srtKey }}
          srtURI: {{ .Values.i7e.sources.files.srtURI }}
          srtBitrate: 1048576
          uploadInfix: files
          uploadDuringInference: false
          uploadResultsDuringInference: true
          retentionEnabled: true
      - vimba:
          enabled: false
          cameraID: DEV_000000000000
          settingsXMLPath: /etc/i7e/DEV_000000000000.xml
          bayerFormat: rggb
          width: 1456
          height: 1088
          deadmanSeconds: 10
          srtKey: mien2aithaipooChitomoxae7Loo5OhH
          srtURI: srt://127.0.0.1:8890
          srtBitrate: 1048576
          uploadInfix: vimba
          uploadDuringInference: false
          uploadResultsDuringInference: true
          retentionEnabled: true
      - aravis:
          enabled: false
          cameraName: Allied Vision Technologies-Mako G-158C (12751)-50-0536959115
          binning: 1
          exposureAuto: Continuous
          gainAuto: Continuous
          width: 1456
          height: 1088
          deadmanSeconds: 10
          srtKey: P2gsDpUMZnM6jBL3QDmJFaVXX4h4tofp
          srtURI: srt://127.0.0.1:8891
          srtBitrate: 1048576
          uploadInfix: aravis
          uploadDuringInference: false
          uploadResultsDuringInference: true
          retentionEnabled: true
      - rtsp:
          enabled: false
          uri: rtsp://foof:barf@192.168.50.14:8554/traf
          width: 1280
          height: 720
          udp: false
          tcp: true
          deadmanSeconds: 10
          srtKey: looj6giiy4Ohp9choogh5uehuf4oe9oh
          srtURI: srt://34.86.126.15:8891
          srtBitrate: 1048576
          uploadInfix: rtsp
          uploadDuringInference: false
          uploadResultsDuringInference: true
          retentionEnabled: true
      - cognex:
          enabled: false
          ip: 192.168.50.131
          user: admin
          password: ""
          width: 800
          height: 600
          deadmanSeconds: 10
          srtKey: mien2aithaipooChitomoxae7Loo5OhH
          srtURI: srt://127.0.0.1:8889
          srtBitrate: 1048576
          uploadDuringInference: false
          uploadResultsDuringInference: true
          retentionEnabled: true
    preprocessWidth: 480
    preprocessHeight: 320
    inference:
      - segmentation:
          enabled: {{ .Values.i7e.segmentation.enabled }}
          configFile: |
            [property]
            # If included, the file MUST exist.  Comment out to force generation of 
            # a new engine file.  NOTE: The generated engine will not have the name
            # specified below, and you'll need to rename it.
            model-engine-file=/var/spool/segment-cars.engine
            onnx-file=/var/spool/segment-cars.onnx
            network-mode=1
            network-type=2
            network-input-order=1
            model-color-format=1
            infer-dims=3;320;480
            output-tensor-meta=1
            segmentation-threshold=0.25
      - objectDetection:
          enabled: {{ .Values.i7e.objectDetection.enabled }}
          configFile: |
            [property]
            # just an id for this model, used to specify this detection as the 
            # primary inference for downstream secondary inference(s).
            gie-unique-id=2
            cluster-mode=3
            # If included, the file MUST exist.  Comment out to force generation of 
            # a new engine file.  NOTE: The generated engine will not have the name
            # specified below, and you'll need to rename it.
            model-engine-file=/var/spool/object-cars.engine
            tlt-encoded-model=/var/spool/object-cars.etlt
            int8-calib-file=/var/spool/object-cars.int8.txt
            # fp 32
            network-mode=1
            network-input-order=0
            # from nvidia sample
            net-scale-factor=0.00392156862745098
            offsets=0.0;0.0;0.0
            infer-dims=3;544;960
            tlt-model-key=tlt_encode
            network-type=0
            num-detected-classes=4
            uff-input-order=0
            output-blob-names=output_cov/Sigmoid;output_bbox/BiasAdd
            uff-input-blob-name=input_1
            model-color-format=0
            maintain-aspect-ratio=0
            output-tensor-meta=0
            threshold=0.1
      - classification:
          enabled: {{ .Values.i7e.classification.enabled }}
          configFile: |
            [property]
            net-scale-factor=1
            model-file=/var/spool/classification.caffemodel
            proto-file=/var/spool/classification.prototxt
            model-engine-file=/var/spool/classification.engine
            mean-file=/var/spool/classification.mean.ppm
            int8-calib-file=/var/spool/classification.cal_trt.bin
            labelfile-path=/etc/i7e/vehicle_class.txt
            force-implicit-batch-dim=1
            batch-size=16
            network-mode=1
            input-object-min-width=16
            input-object-min-height=16
            model-color-format=1
            # primary (1) or secondary (2).  Primary classifies the full image.
            process-mode=2
            gpu-id=0
            gie-unique-id=4
            # The gie-unique-id of an object-detection inference plugin on whose
            # results classifications will be run if process-mode is 2.
            operate-on-gie-id=2
            operate-on-class-ids=0
            is-classifier=1
            output-blob-names=predictions/Softmax
            classifier-threshold=0.001
          tracker:
            enabled: false
            width: 640
            height: 384
            libraryFile: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
            configFile: /etc/i7e/config_tracker.yaml
            trackingSurfaceType: 0
            computeHardware: 0
            trackingIdResetMode: 0
          analytics:
            - enabled: true
              sourceIndexes:
                - 2
              width: 1000
              height: 1000
              lineCrossings:
                adherence: LOOSE
                extended: true
                classes:
                  - 0
                  - 1
                  - 3
                  - 4
                vectors:
                  - label: LEFT_LANE_FROM_RIGHT
                    lineStartPoint:
                      x: 10
                      "y": 0
                    lineEndPoint:
                      x: 390
                      "y": 500
                    directionStartPoint:
                      x: 1000
                      "y": 750
                    directionEndPoint:
                      x: 0
                      "y": 750
                  - label: RIGHT_LANE_FROM_LEFT
                    lineStartPoint:
                      x: 10
                      "y": 0
                    lineEndPoint:
                      x: 390
                      "y": 500
                    directionStartPoint:
                      x: 0
                      "y": 750
                    directionEndPoint:
                      x: 1000
                      "y": 750
              direction:
                adherence: BALANCED
                classes:
                  - 0
                  - 1
                  - 3
                  - 4
                vectors:
                  - startPoint:
                      x: 1000
                      "y": 500
                    endPoint:
                      x: 0
                      "y": 500
                    label: left
                  - endPoint:
                      x: 1000
                      "y": 500
                    startPoint:
                      x: 0
                      "y": 500
                    label: right
              roi:
                inverse: false
                classes:
                  - 0
                  - 1
                  - 3
                  - 4
                regions:
                  - label: UL
                    polygon:
                      - x: 0
                        "y": 0
                      - x: 499
                        "y": 0
                      - x: 499
                        "y": 499
                      - x: 0
                        "y": 499
                  - label: UR
                    polygon:
                      - x: 500
                        "y": 0
                      - x: 1000
                        "y": 0
                      - x: 1000
                        "y": 499
                      - x: 500
                        "y": 499
                  - label: LL
                    polygon:
                      - x: 0
                        "y": 500
                      - x: 499
                        "y": 500
                      - x: 499
                        "y": 1000
                      - x: 0
                        "y": 1000
                  - label: LR
                    polygon:
                      - x: 500
                        "y": 500
                      - x: 1000
                        "y": 500
                      - x: 1000
                        "y": 1000
                      - x: 500
                        "y": 1000
          extraFiles:
            - name: vehicle_class.txt
              contents: coupe;largevehicle;sedan;suv;truck;van
            - name: config_tracker.yaml
              contents: |
                %YAML:1.0
                BaseConfig:
                  minDetectorConfidence: 0
                TargetManagement:
                  enableBboxUnClipping: 1
                  maxTargetsPerStream: 150
                  minIouDiff4NewTarget: 0.5
                  minTrackerConfidence: 0.2
                  probationAge: 3
                  maxShadowTrackingAge: 30
                  earlyTerminationAge: 1
                TrajectoryManagement:
                  useUniqueID: 0
                DataAssociator:
                  dataAssociatorType: 0
                  associationMatcherType: 0
                  checkClassMatch: 1
                  minMatchingScore4Overall: 0.0
                  minMatchingScore4SizeSimilarity: 0.6
                  minMatchingScore4Iou: 0.0
                  minMatchingScore4VisualSimilarity: 0.7
                  matchingScoreWeight4VisualSimilarity: 0.6
                  matchingScoreWeight4SizeSimilarity: 0.0
                  matchingScoreWeight4Iou: 0.4
                StateEstimator:
                  stateEstimatorType: 1
                  processNoiseVar4Loc: 2.0
                  processNoiseVar4Size: 1.0
                  processNoiseVar4Vel: 0.1
                  measurementNoiseVar4Detector: 4.0
                  measurementNoiseVar4Tracker: 16.0
                VisualTracker:
                  visualTrackerType: 1
                  useColorNames: 1
                  useHog: 0
                  featureImgSizeLevel: 2
                  featureFocusOffsetFactor_y: -0.2
                  filterLr: 0.075
                  filterChannelWeightsLr: 0.1
                  gaussianSigma: 0.75
{{ range $camera := .Values.i7e.cameras }}
  {{ $camera.name }}.xml: |
{{ $camera.vimbaXML | indent 4 }}
{{ end }}
